output "vm_public_ip" {
  description = "Public IPv4 assigned to the Asterisk VM."
  value       = azurerm_public_ip.this.ip_address
}

output "vm_fqdn" {
  description = "Public FQDN generated by Azure for the VM public IP."
  value       = azurerm_public_ip.this.fqdn
}

output "ssh_connect_command" {
  description = "SSH command template to connect to the VM."
  value       = "ssh ${var.admin_username}@${azurerm_public_ip.this.ip_address}"
}

output "asterisk_service_status_hint" {
  description = "Command to verify Asterisk status once connected."
  value       = "sudo systemctl status asterisk --no-pager && sudo asterisk -rx 'core show version'"
}