all:
  hosts:
    asterisk_vm:
      ansible_host: 20.124.1.120
      ansible_user: azureuser
      ansible_port: 22
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /home/valen17/.ssh/asterisk_vm_ed25519
