output "vm_public_ip" {
  description = "Public IPv4 assigned to the LiveKit SIP VM."
  value       = azurerm_public_ip.this.ip_address
}

output "vm_fqdn" {
  description = "Public FQDN generated by Azure for the VM public IP."
  value       = azurerm_public_ip.this.fqdn
}

output "ssh_connect_command" {
  description = "SSH command template to connect to the VM."
  value       = "ssh ${var.admin_username}@${azurerm_public_ip.this.ip_address}"
}

output "sip_uri" {
  description = "SIP URI endpoint for LiveKit SIP trunk configuration."
  value       = "${azurerm_public_ip.this.ip_address}:${var.sip_port}"
}